MetaMedia/MetaMedia/Models/ErrorViewModel.cs
namespace MetaMedia.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MetaMedia/MetaMedia/Controllers/HomeController.cs
using MetaMedia.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MetaMedia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MetaMedia/MetaMedia/Controllers/WorksController.cs
using MediaData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MetaMedia.Controllers
{
    public class WorksController : Controller
    {

        private readonly DataDBContext _context;

        public WorksController(DataDBContext context)
        {
            _context = context;
        }

        // GET: WorksController
        public ActionResult Index()
        {
            return View();
        }

        // GET: WorksController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WorksController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorksController/Create
        [HttpPost]
        // [ValidateAntiForgeryToken] 
        [HttpPost]
        public ActionResult Create(Work work)
        {
            if (ModelState.IsValid)
            {
                _context.Works.Add(work);
                _context.SaveChanges();

                // Redirigez vers une autre action après la sauvegarde
                return RedirectToAction("Index"); // Changez "Index" par la vue appropriée
            }

            return View(work);
        }


        // GET: WorksController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WorksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WorksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WorksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MetaMedia/MetaMedia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MetaMedia/MetaMedia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MetaMedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MetaMedia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MetaMedia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MetaMedia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MetaMedia/MetaMedia/Views/Works/Index.cshtml
@model MediaData.Work

@{
    ViewBag.Title = "Ajouter un Média";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Works", FormMethod.Post))
{
    @Html.AntiForgeryToken()

        <div class="form-group">
        @Html.LabelFor(model => model.Title)
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.ReleaseDate)
        @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
        @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.Genre)
        @Html.EditorFor(model => model.Genre)
        @Html.ValidationMessageFor(model => model.Genre)
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.Description)
        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = 5 } })
        @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.ImageURL)
        @Html.EditorFor(model => model.ImageURL)
        @Html.ValidationMessageFor(model => model.ImageURL)
        </div>

        <button type="submit" class="btn btn-primary">Ajouter</button>
}